target-version = "py311"
line-length = 120

[lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[lint.per-file-ignores]
"tools/build.py" = ["E402"]
"tools/run_presubmit.py" = ["E402"]
"tools/setup_presubmit.py" = ["E402"]
